# Generated by Django 5.2.17 on 2026-09-17 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('name', models.CharField(max_length=150, verbose_name='razão social')),
                ('trade_name', models.CharField(blank=True, max_length=150, verbose_name='nome fantasia')),
                ('cnpj', models.CharField(blank=True, max_length=18, verbose_name='CNPJ')),
                ('contact', models.CharField(blank=True, max_length=100, verbose_name='contato')),
                ('phone', models.CharField(blank=True, max_length=25, verbose_name='telefone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('address', models.TextField(blank=True, verbose_name='endereço')),
                ('products', models.TextField(blank=True, verbose_name='produtos fornecidos')),
                ('payment_terms', models.CharField(blank=True, max_length=200, verbose_name='condições de pagamento')),
                ('active', models.BooleanField(default=True, verbose_name='ativo')),
            ],
            options={
                'verbose_name': 'fornecedor',
                'verbose_name_plural': 'fornecedores',
                'ordering': ['name'],
            },
        ),
    ]
