# Generated by Django 5.2.17 on 2026-09-17 13:48

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('core', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='valor')),
                ('paid_on', models.DateField(default=django.utils.timezone.localdate, verbose_name='data')),
                ('method', models.CharField(choices=[('pix', 'PIX'), ('cash', 'Dinheiro'), ('credit', 'Crédito'), ('debit', 'Débito'), ('boleto', 'Boleto'), ('insurance', 'Convênio'), ('transfer', 'Transferência')], max_length=20, verbose_name='forma de pagamento')),
                ('is_refund', models.BooleanField(default=False)),
                ('note', models.CharField(blank=True, max_length=250, verbose_name='observação / motivo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'pagamento',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('direction', models.CharField(choices=[('in', 'Receita'), ('out', 'Despesa')], max_length=3, verbose_name='tipo')),
                ('category', models.CharField(choices=[('service', 'Atendimento'), ('fixed', 'Despesa fixa'), ('variable', 'Despesa variável'), ('direct', 'Custo direto'), ('tax', 'Imposto'), ('commission', 'Comissão'), ('purchase', 'Compra de estoque'), ('other', 'Outros')], default='service', max_length=20, verbose_name='categoria')),
                ('description', models.CharField(max_length=200, verbose_name='descrição')),
                ('cost_center', models.CharField(blank=True, max_length=100, verbose_name='centro de custo')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='valor bruto')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='desconto')),
                ('issue_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='emissão')),
                ('due_date', models.DateField(verbose_name='vencimento')),
                ('method', models.CharField(choices=[('pix', 'PIX'), ('cash', 'Dinheiro'), ('credit', 'Crédito'), ('debit', 'Débito'), ('boleto', 'Boleto'), ('insurance', 'Convênio'), ('transfer', 'Transferência')], default='pix', max_length=20, verbose_name='método previsto')),
                ('installment_group', models.UUIDField(blank=True, editable=False, null=True)),
                ('installment_number', models.PositiveIntegerField(default=1, editable=False)),
                ('cancelled', models.BooleanField(default=False, editable=False)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='appointments.appointment')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.branch', verbose_name='unidade')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='patients.patient', verbose_name='paciente')),
            ],
            options={
                'verbose_name': 'lançamento',
                'verbose_name_plural': 'lançamentos',
                'ordering': ['due_date', 'pk'],
            },
        ),
    ]
