# Generated by Django 5.2.17 on 2026-09-17 13:48

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('inventory', '0001_initial'),
        ('suppliers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('order_date', models.DateField(verbose_name='data do pedido')),
                ('expected_date', models.DateField(verbose_name='previsão de entrega')),
                ('due_date', models.DateField(verbose_name='vencimento')),
                ('invoice_number', models.CharField(blank=True, max_length=80, verbose_name='nota fiscal')),
                ('payment_method', models.CharField(blank=True, max_length=70, verbose_name='forma de pagamento')),
                ('status', models.CharField(choices=[('draft', 'Aberto'), ('ordered', 'Enviado'), ('received', 'Recebido'), ('cancelled', 'Cancelado')], default='draft', max_length=20, verbose_name='status')),
                ('received_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.branch', verbose_name='unidade')),
                ('responsible', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='suppliers.supplier', verbose_name='fornecedor')),
            ],
            options={
                'verbose_name': 'pedido de compra',
            },
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='quantidade')),
                ('unit_cost', models.DecimalField(decimal_places=4, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='custo unitário')),
                ('batch_number', models.CharField(max_length=70, verbose_name='lote')),
                ('expiry', models.DateField(blank=True, null=True, verbose_name='validade')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product', verbose_name='material')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='purchases.purchase', verbose_name='pedido')),
            ],
            options={
                'verbose_name': 'item de compra',
            },
        ),
    ]
