# Generated by Django 5.2.17 on 2026-09-17 13:48

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('patients', '0001_initial'),
        ('professionals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('name', models.CharField(max_length=150, verbose_name='nome')),
                ('category', models.CharField(max_length=100, verbose_name='categoria')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('duration', models.PositiveIntegerField(default=30, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(480)], verbose_name='duração (minutos)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='preço por sessão')),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='outros custos diretos por sessão (sem materiais/comissões)')),
                ('specialty', models.CharField(blank=True, max_length=100, verbose_name='especialidade')),
                ('sessions', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='sessões')),
                ('active', models.BooleanField(default=True, verbose_name='ativo')),
                ('professionals', models.ManyToManyField(blank=True, to='professionals.professional', verbose_name='dentistas habilitados (vazio: todos)')),
            ],
            options={
                'verbose_name': 'procedimento',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TreatmentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('name', models.CharField(max_length=150, verbose_name='título')),
                ('status', models.CharField(choices=[('proposed', 'Proposto'), ('accepted', 'Aceito'), ('ongoing', 'Em andamento'), ('completed', 'Concluído'), ('cancelled', 'Cancelado')], default='proposed', max_length=20, verbose_name='status')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='desconto total')),
                ('payment_method', models.CharField(blank=True, max_length=80, verbose_name='forma de pagamento')),
                ('installments', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)], verbose_name='parcelas')),
                ('acceptance', models.TextField(blank=True, verbose_name='registro do aceite')),
                ('accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='aceito em')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plans', to='patients.patient', verbose_name='paciente')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='professionals.professional', verbose_name='dentista')),
            ],
            options={
                'verbose_name': 'plano de tratamento',
            },
        ),
        migrations.CreateModel(
            name='PlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('teeth', models.CharField(blank=True, max_length=100, verbose_name='dentes envolvidos')),
                ('sessions', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='sessões previstas')),
                ('completed_sessions', models.PositiveIntegerField(default=0, editable=False, verbose_name='sessões concluídas')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='preço por sessão')),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='treatments.procedure', verbose_name='procedimento')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='treatments.treatmentplan', verbose_name='plano')),
            ],
            options={
                'verbose_name': 'item do tratamento',
            },
        ),
        migrations.CreateModel(
            name='ProcedureMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='quantidade por sessão')),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materials', to='treatments.procedure', verbose_name='procedimento')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product', verbose_name='material')),
            ],
            options={
                'verbose_name': 'material do procedimento',
                'constraints': [models.UniqueConstraint(fields=('procedure', 'product'), name='procedure_material_unique')],
            },
        ),
    ]
