# Generated by Django 5.2.17 on 2026-09-17 13:48

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Professional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('name', models.CharField(max_length=140, verbose_name='nome')),
                ('specialty', models.CharField(max_length=120, verbose_name='especialidade')),
                ('cro', models.CharField(max_length=30, unique=True, verbose_name='CRO / UF')),
                ('phone', models.CharField(blank=True, max_length=25, verbose_name='telefone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('commission_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='comissão (%)')),
                ('commission_fixed', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='comissão fixa (substitui percentual)')),
                ('active', models.BooleanField(default=True, verbose_name='ativo')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='professional', to=settings.AUTH_USER_MODEL, verbose_name='usuário dentista')),
            ],
            options={
                'verbose_name': 'profissional',
                'verbose_name_plural': 'profissionais',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Segunda'), (1, 'Terça'), (2, 'Quarta'), (3, 'Quinta'), (4, 'Sexta'), (5, 'Sábado'), (6, 'Domingo')], verbose_name='dia da semana')),
                ('start_time', models.TimeField(verbose_name='início')),
                ('end_time', models.TimeField(verbose_name='fim')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='working_hours', to='professionals.professional', verbose_name='dentista')),
            ],
            options={
                'verbose_name': 'horário de atendimento',
                'verbose_name_plural': 'horários de atendimento',
            },
        ),
        migrations.CreateModel(
            name='ScheduleBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('start', models.DateTimeField(verbose_name='início')),
                ('end', models.DateTimeField(verbose_name='fim')),
                ('reason', models.CharField(max_length=250, verbose_name='motivo')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='professionals.professional', verbose_name='dentista')),
            ],
            options={
                'verbose_name': 'bloqueio de agenda',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('name', models.CharField(max_length=90, verbose_name='nome')),
                ('active', models.BooleanField(default=True, verbose_name='ativo')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.branch', verbose_name='unidade')),
            ],
            options={
                'verbose_name': 'consultório',
                'constraints': [models.UniqueConstraint(fields=('name', 'branch'), name='room_branch_unique')],
            },
        ),
    ]
