# Generated by Django 5.2.17 on 2026-09-17 13:48

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('number', models.CharField(max_length=70, verbose_name='lote')),
                ('expiry', models.DateField(blank=True, null=True, verbose_name='validade')),
                ('quantity', models.DecimalField(decimal_places=3, default=0, editable=False, max_digits=12, verbose_name='saldo')),
                ('unit_cost', models.DecimalField(decimal_places=4, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='custo unitário')),
            ],
            options={
                'verbose_name': 'lote',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('name', models.CharField(max_length=150, verbose_name='nome')),
                ('category', models.CharField(max_length=100, verbose_name='categoria')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='código interno')),
                ('barcode', models.CharField(blank=True, max_length=70, verbose_name='código de barras')),
                ('unit', models.CharField(default='un', max_length=15, verbose_name='unidade de medida')),
                ('minimum', models.DecimalField(decimal_places=3, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='estoque mínimo')),
                ('maximum', models.DecimalField(decimal_places=3, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='estoque máximo (zero: não definido)')),
                ('manufacturer', models.CharField(blank=True, max_length=100, verbose_name='fabricante')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='local de armazenamento')),
                ('active', models.BooleanField(default=True, verbose_name='ativo')),
            ],
            options={
                'verbose_name': 'material',
                'verbose_name_plural': 'materiais',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('entry', 'Entrada'), ('purchase', 'Compra'), ('manual', 'Saída manual'), ('procedure', 'Consumo em procedimento'), ('adjustment', 'Ajuste'), ('loss', 'Perda'), ('expired', 'Vencimento'), ('return', 'Devolução')], max_length=20, verbose_name='tipo')),
                ('delta', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='variação')),
                ('unit_cost', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='custo registrado')),
                ('balance_after', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='saldo após')),
                ('reason', models.CharField(max_length=250, verbose_name='motivo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='data')),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='responsável')),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='appointments.appointment')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.batch', verbose_name='lote')),
            ],
            options={
                'verbose_name': 'movimentação',
                'verbose_name_plural': 'movimentações',
                'ordering': ['-created_at'],
            },
        ),
    ]
