# Generated by Django 5.2.17 on 2026-09-17 13:48

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('start', models.DateTimeField(verbose_name='início')),
                ('end', models.DateTimeField(verbose_name='fim')),
                ('value', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='valor da sessão')),
                ('payment_method', models.CharField(choices=[('pix', 'PIX'), ('cash', 'Dinheiro'), ('credit', 'Crédito'), ('debit', 'Débito'), ('boleto', 'Boleto'), ('insurance', 'Convênio'), ('transfer', 'Transferência')], default='pix', max_length=20, verbose_name='forma de pagamento')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('confirmed', 'Confirmado'), ('in_progress', 'Em atendimento'), ('completed', 'Concluído'), ('cancelled', 'Cancelado'), ('missed', 'Não compareceu'), ('rescheduled', 'Reagendado')], default='pending', max_length=20, verbose_name='status')),
                ('notes', models.TextField(blank=True, verbose_name='observações administrativas')),
                ('fit_in', models.BooleanField(default=False, verbose_name='encaixe fora do expediente')),
                ('fit_in_reason', models.CharField(blank=True, max_length=250, verbose_name='justificativa do encaixe')),
                ('cancellation_reason', models.CharField(blank=True, max_length=250, verbose_name='motivo do cancelamento')),
                ('recurrence_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('completed_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('material_cost', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('other_direct_cost', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('commission', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='patients.patient', verbose_name='paciente')),
            ],
            options={
                'verbose_name': 'consulta',
                'ordering': ['start'],
            },
        ),
    ]
