# Generated by Django 5.2.17 on 2026-09-17 13:48

import clinical_records.models
import core.crypto
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        ('professionals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180, verbose_name='título')),
                ('category', models.CharField(choices=[('clinical', 'Clínico'), ('document', 'Administrativo'), ('receipt', 'Comprovante')], max_length=20, verbose_name='tipo')),
                ('file', models.FileField(upload_to=clinical_records.models.upload_path, validators=[clinical_records.models.validate_file], verbose_name='arquivo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to='patients.patient', verbose_name='paciente')),
            ],
            options={
                'verbose_name': 'anexo',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClinicalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('anamnesis', 'Anamnese'), ('evolution', 'Evolução'), ('diagnosis', 'Diagnóstico'), ('prescription', 'Prescrição / orientação'), ('certificate', 'Atestado / declaração'), ('tooth', 'Odontograma'), ('correction', 'Retificação')], max_length=20, verbose_name='tipo')),
                ('text', core.crypto.EncryptedTextField(verbose_name='registro clínico')),
                ('allergies', core.crypto.EncryptedTextField(blank=True, verbose_name='alergias')),
                ('conditions', core.crypto.EncryptedTextField(blank=True, verbose_name='doenças preexistentes')),
                ('medicines', core.crypto.EncryptedTextField(blank=True, verbose_name='medicamentos em uso')),
                ('tooth', models.CharField(blank=True, max_length=2, verbose_name='dente (FDI)')),
                ('surface', models.CharField(blank=True, max_length=40, verbose_name='face / região')),
                ('condition', models.CharField(blank=True, choices=[('healthy', 'Hígido'), ('caries', 'Cárie'), ('restored', 'Restaurado'), ('missing', 'Ausente'), ('planned', 'Tratamento indicado'), ('treated', 'Tratado')], max_length=20, verbose_name='condição')),
                ('digest', models.CharField(editable=False, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clinical_entries', to='patients.patient', verbose_name='paciente')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='professionals.professional', verbose_name='dentista responsável')),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='corrections', to='clinical_records.clinicalentry', verbose_name='retifica registro')),
            ],
            options={
                'verbose_name': 'registro clínico',
                'ordering': ['-created_at'],
            },
        ),
    ]
