# Generated by Django 5.2.17 on 2026-09-17 13:48

import patients.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('name', models.CharField(max_length=160, verbose_name='nome completo')),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, unique=True, validators=[patients.models.validate_cpf], verbose_name='CPF')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='nascimento')),
                ('phone', models.CharField(blank=True, max_length=25, verbose_name='telefone / WhatsApp')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('address', models.TextField(blank=True, verbose_name='endereço')),
                ('gender', models.CharField(blank=True, max_length=60, verbose_name='gênero')),
                ('occupation', models.CharField(blank=True, max_length=100, verbose_name='profissão')),
                ('insurance', models.CharField(blank=True, max_length=100, verbose_name='convênio')),
                ('insurance_number', models.CharField(blank=True, max_length=80, verbose_name='carteirinha')),
                ('emergency_contact', models.CharField(blank=True, max_length=180, verbose_name='contato de emergência')),
                ('notes', models.TextField(blank=True, verbose_name='observações administrativas')),
                ('active', models.BooleanField(default=True, verbose_name='ativo')),
                ('privacy_acknowledged', models.BooleanField(default=False, verbose_name='ciência da política de privacidade registrada')),
                ('privacy_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('reminder_consent', models.BooleanField(default=False, verbose_name='autoriza lembretes')),
                ('anonymized_at', models.DateTimeField(blank=True, editable=False, null=True)),
            ],
            options={
                'verbose_name': 'paciente',
                'ordering': ['name'],
            },
        ),
    ]
